apiVersion: v1
kind: Pod
metadata:
  name: nginxpvc
  label:
   app: myapp
   env: dev
spec:
  containers:
   - name: nginx
     image: nginx:alpine
  
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
